### ISSUE TITLE
Error during model creation in AnyLogic

### ISSUE THREAD

**Issue by djangozho** [t-wolfeadam/AnyLogic-Pypeline#53]
Hallo,

When I followed the Quick start guide creating model in AnyLogic,
there was something wrong when I run the model.

Error during model creation:
com/anylogic/engine/presentation/ColorConstants
Caused by: com.anylogic.engine.presentation.ColorConstants
java.lang.NoClassDefFoundError: com/anylogic/engine/presentation/ColorConstants
	at com.anylogic.libraries.pypeline.Jsonifier.<clinit>(Jsonifier.java:1955)
	at model1.Main.instantiate_pyCommunicator_xjal(Main.java:125)
	at model1.Main.instantiateBaseStructureThis_xjal(Main.java:263)
	at model1.Main.<init>(Main.java:246)
	at model1.Simulation.createRoot(Simulation.java:155)
	at model1.Simulation.createRoot(Simulation.java:1)
Caused by: java.lang.ClassNotFoundException: com.anylogic.engine.presentation.ColorConstants
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more

Thanks for your support.
Best Regards

**Comment by vutle** [comment]
I have the same error using Anylogic 8.8.1

**Comment by djangozho** [comment]
I solved the problem in using AnyLogic 8.8.3

**Comment by vutle** [comment]
Thanks, that problem was also fixed in AnyLogic 8.8.4.
